---
include:
  - board: crosses_v2_left
    artifact-name: crosses_v2_36_left
  - board: crosses_v2_right
    artifact-name: crosses_v2_36_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: crosses_v2_right
    artifact-name: crosses_v2_settings_reset
    shield: settings_reset
